### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by cbetta** [interfax/contributor-instructions#1]
@if-adam In class names do we prefer `InterFAX` or `Interfax`? I see `InterFAX` used in all branding, but the downside is that this will lead to the following file name in some languages: `inter_fax` as that is the snake_case version of `InterFAX`

**Comment by cbetta** [comment]
It seems `Interfax` is used in the C# lib

**Comment by UPIF-Marketing** [comment]
@cbetta InterFAX is the brand, but this shouldn't come in the way of sane naming in code.

Use either Interfax or whatever is the right case for your language.
