### ISSUE TITLE
Name/email for contribution

### ISSUE THREAD

**Issue by cbetta** [interfax/contributor-instructions#2]
@if-adam Many package managers will require a name and email for listing the contributors. It would be good to list `InterFAX`. What email can we use for this? `developer@interfax.net`?

**Comment by UPIF-Marketing** [comment]
dev@interfax.net

And if you need to submit a URL, https://www.interfax.net/en/dev

**Comment by cbetta** [comment]
Cool. I'll add this to the doc when I do a PR.
