### ISSUE TITLE
Account balance

### ISSUE THREAD

**Issue by cbetta** [interfax/contributor-instructions#4]
Does InterFAX have a default currency?

Currently I have this:

``` rb
client.account.balance
=> 9.86
```

And I am wondering  if we should add the currency to the output. E.g.

``` rb
client.account.balance
=> 9.86 USD
```

**Comment by UPIF-Marketing** [comment]
@cbetta No, the currency is account-dependent. When someone registers (either as a developer or as a paid account), they provide their country of residence which determines a.) the currency, and b.) the dealer that will provide (non-developer) support.

So, as defined in the [documentation](https://www.interfax.net/en/dev/rest/reference/3001), what's returned is the "_Value of outstanding outbound credits in account, in the account's currency._"

You might ask, how does a developer know the currency that was determined for him? That's done by visiting the control panel and clicking Account > Billing transactions. The currency is displayed there.

**Comment by cbetta** [comment]
@if-adam interesting. I guess this will do for now then
