### ISSUE TITLE
Inbound fax methods

### ISSUE THREAD

**Issue by cbetta** [interfax/contributor-instructions#5]
@if-adam currently your document only lists the listing of faxes for inbound faxes, do we want to implement getting a single fax record, the email and image, and resending/marking them as well?

**Comment by UPIF-Marketing** [comment]
@cbetta 

> your document only lists the listing of faxes for inbound faxes

Please use the .net code as reference, where this is indeed handled. The documentation needs this requirement added, if it isn't defined.

**Comment by cbetta** [comment]
@if-adam we should have a chat about this on hangout. The `.NET` code is hard to decipher for someone not familiar with it.
